language: ruby
before_script:
  - "mysql -e 'create database lhm;'"
rvm:
  - 2.0.0
  - 2.1
sudo: false
gemfile:
  - gemfiles/ar-4.0_mysql2.gemfile
  - gemfiles/ar-4.1_mysql2.gemfile
  - gemfiles/ar-4.2_mysql2.gemfile
